// El iceberg del especismo — SSOT de los nodos. Se engorda hilo a hilo.
// level: 0 = superficie (lo que se oye) … 5 = fondo. Las citas van verbatim (en);
// la prosa del nodo va en español. `from` = de qué nodos superiores emerge.
window.ICEBERG = {
  levels: [
    { id: 0, name: 'Lo que se oye',        sub: 'Las frases tal cual llegan a los grupos. Suenan a sentido común.' },
    { id: 1, name: 'Lo que presuponen',    sub: 'El salto escondido en cada frase: de un hecho a un permiso.' },
    { id: 2, name: 'Lo que se hace',       sub: 'El mecanismo material que esas premisas mantienen andando.' },
    { id: 3, name: 'Cómo se defiende',     sub: 'Las maniobras que aparecen cuando se pregunta por el título.' },
    { id: 4, name: 'Cómo se reproduce',    sub: 'Por qué nadie tiene que decidirlo: se hereda antes de poder preguntar.' },
    { id: 5, name: 'El fondo',             sub: 'Lo que queda cuando se apaga la luz.' },
  ],
  nodes: [
    // ── 0 · superficie ──────────────────────────────────────────────────────
    { id: 'its-food', level: 0, title: '"It\'s food."',
      quote: 'It\'s food.', src: 'Vegans V\'s Meat Eaters · jun 2026',
      body: 'La respuesta más corta del grupo. Nombra al animal por su destino y da por cerrada la pregunta de por qué ese destino es legítimo.',
      tactics: ['peticion_de_principio'], from: [] },
    { id: 'omnivores', level: 0, title: '"Humans are omnivores."',
      quote: 'It\'s really very simple. Humans are omnivores and eat meat and plant matter.', src: 'Vegans V\'s Meat Eaters · jun 2026',
      body: 'Una descripción biológica ofrecida como si fuera un permiso moral. Los omnívoros también comen carroña; nadie defiende eso.',
      tactics: ['naturalismo', 'is_ought'], from: [] },
    { id: 'designed', level: 0, title: '"Biologically designed to eat."',
      quote: 'There is nothing immoral about eating the way we are biologically designed to eat.', src: 'Vegans V\'s Meat Eaters · jun 2026',
      body: 'El "diseño" hace el trabajo: si la biología lo manda, nadie tiene que justificarlo.',
      tactics: ['naturalismo', 'is_ought'], from: [] },
    { id: 'cow-gives', level: 0, title: '"The cow gives milk."',
      quote: 'One definition of give is to "yield a product". Your entire premise is, again, based on ignorance.', src: 'Vegans V\'s Meat Eaters · ago 2026',
      body: 'El verbo del regalo. Su propio diccionario lo delata: "yield a product" es lo que se dice de campos, minas y máquinas — de cosas.',
      tactics: ['domestication_mutualism'], from: [] },
    { id: 'subjective', level: 0, title: '"Morality is subjective."',
      quote: 'I defend nothing… I won\'t justify it because there is no one to justify it to. Morality is subjective.', src: 'Vegans V\'s Meat Eaters · jun 2026',
      body: 'La línea que cierra la conversación sin haber entrado a ella. Nunca se usa cuando lo que está en juego es del que la dice.',
      tactics: ['relativismo_moral'], from: [] },
    { id: 'taste', level: 0, title: '"I just like the taste."',
      quote: 'I just like the taste.', src: 'varios hilos',
      body: 'Una preferencia presentada como si zanjara una pregunta sobre otro.',
      tactics: ['preferencia_gusto'], from: [] },
    { id: 'good-life', level: 0, title: '"They have a good life."',
      quote: 'The cows go in to be milked of their own accord as many times a day as they want to.', src: 'Vegans V\'s Meat Eaters · ago 2026',
      body: 'La fila voluntaria al robot ordeñador como prueba de que no hay apropiación. Lo que se ve es un alivio; lo que no se ve es quién fabricó la presión.',
      tactics: ['welfare_rhetoric'], from: [] },
    { id: 'more-valuable', level: 0, title: '"Human life is worth more."',
      quote: 'Human life is far more valuable than animal life, therefore exploitation is justified.', src: 'Vegans V\'s Meat Eaters · jun 2026',
      body: 'La jerarquía afirmada como premisa. El criterio que la sostiene nunca se nombra.',
      tactics: ['species_hierarchy'], from: [] },

    // ── 1 · lo que presuponen ──────────────────────────────────────────────
    { id: 'can-should', level: 1, title: 'Poder → deber',
      body: 'De "podemos comerlos" a "está bien comerlos" hay un salto que ninguna frase de la superficie da. Ser capaz de algo no dice nada sobre si hay que hacerlo.',
      tactics: ['is_ought', 'naturalismo'], frameworks: ['dominacion-no-es-superioridad-moral', 'tabula-rasa-ni-nacemos-ni-nos-hacen'], from: ['omnivores', 'designed'] },
    { id: 'normal-just', level: 1, title: 'Normal → justo',
      body: 'Que casi todos lo hagan describe cuánta gente lo hace. La esclavitud humana también fue lo normal, lo legal y lo que hacía la mayoría.',
      tactics: ['apelacion_normal', 'apelacion_mayoria'], frameworks: ['njn-normal-justo-necesario', 'extranar-lo-naturalizado'], from: ['its-food', 'taste'] },
    { id: 'thing-not-someone', level: 1, title: 'Algo, no alguien',
      body: 'Para que "es comida" funcione, el animal tiene que ser una cosa. Pero un cerdo teme, busca seguir vivo y tiene un punto de vista: es alguien. La palabra "comida" borra eso antes de que se pueda preguntar.',
      tactics: ['peticion_de_principio', 'species_hierarchy'], frameworks: ['algo-a-alguien-sujeto-derecho'], from: ['its-food', 'more-valuable', 'cow-gives'] },
    { id: 'criterion-unnamed', level: 1, title: 'El criterio que nadie nombra',
      body: 'Si vale más por razonar, hablar o entender la muerte, entonces un bebé o una persona con demencia valdrían menos — y nadie acepta eso. El único criterio que sobrevive es sentir.',
      tactics: ['criterio_capacidad_superior', 'pertenencia_de_clase'], frameworks: ['sobreposicion-de-especies-criterio-leido'], from: ['more-valuable'] },
    { id: 'one-way-relativism', level: 1, title: 'Relativismo de un solo sentido',
      body: 'Nadie es relativista con su coche, su salario o sus hijos. La "subjetividad" aparece solo para el lado que pierde. Eso no es una tesis: es un escudo.',
      tactics: ['relativismo_moral'], frameworks: ['respetar-no-es-opcion', 'conocimiento-compromete'], from: ['subjective'] },
    { id: 'welfare-consent', level: 1, title: 'Bienestar como consentimiento',
      body: 'Que la vaca haga fila al robot alivia una presión fabricada: una ubre criada a diez veces lo que tomaría su cría, y la cría removida. Voluntariedad dentro de condiciones diseñadas no toca el título.',
      tactics: ['welfare_rhetoric', 'domestication_mutualism'], frameworks: ['premisa-falsa-los-animales-nos-dan', 'domesticar-eufemismo-dominar'], from: ['good-life', 'cow-gives'] },

    // ── 2 · lo que se hace ─────────────────────────────────────────────────
    { id: 'property', level: 2, title: 'El estatus de propiedad',
      body: 'Un sujeto traído a existir, tenido como cosa que pertenece a alguien, y dispuesto en fecha. No es una versión grande de la cosechadora que mata ratones: ahí hay una baja; aquí hay alguien poseído desde el nacimiento.',
      tactics: ['crop_deaths_flip'], frameworks: ['esclavitud-paralelismo', 'algo-a-alguien-sujeto-derecho'], from: ['thing-not-someone', 'normal-just'] },
    { id: 'manufactured-availability', level: 2, title: 'Disponibilidad fabricada',
      body: '"Los criamos para eso" explica de dónde viene el sistema y se ofrece como la razón de que sea legítimo. Fabricar la disponibilidad de un cuerpo es exactamente lo que se está cuestionando.',
      tactics: ['domestication_mutualism', 'welfare_rhetoric'], frameworks: ['domesticar-eufemismo-dominar'], from: ['welfare-consent', 'can-should'] },
    { id: 'necessary', level: 2, title: 'La palabra "necesario"',
      body: 'Casi toda defensa aterriza en esa palabra: la proteína, la tierra, los campos que también matan. Concedido todo, lo que "necesario" defiende no es reducir nada — es poseer. ¿Existe la esclavitud necesaria?',
      tactics: ['futility_no_clean_option', 'crop_deaths_flip'], frameworks: ['no-necesidad-cambiaron-las-reglas', 'violencia-indirecta-quien-demanda'], from: ['can-should', 'property'] },
    { id: 'infrastructure', level: 2, title: 'La infraestructura',
      body: 'Subsidios, cadenas de frío, rastros, escuelas de veterinaria, menús infantiles. La violencia no la hace nadie en particular: está construida, y por eso parece que no la hace nadie.',
      tactics: ['libertarian_autonomy', 'futility_no_clean_option'], frameworks: ['violencia-estructural-infraestructura', 'economia-especista-heredada'], from: ['normal-just', 'property'] },

    // ── 3 · cómo se defiende ───────────────────────────────────────────────
    { id: 'welfarism-master-move', level: 3, title: 'El bienestarismo como jugada maestra',
      body: 'Mientras la discusión sea cuánto sufre, el título de propiedad queda intacto. "Trato humanitario" y "muerte sin dolor" son la concesión que el sistema hace para no tener que responder por qué posee.',
      tactics: ['welfare_rhetoric', 'concesion_reframe_policy'], frameworks: ['bienestarismo-jugada-maestra-del-poder', 'semaforo-rojo-amarillo-welfarismo'], from: ['welfare-consent', 'property'] },
    { id: 'retreat-cycle', level: 3, title: 'La retirada en cadena',
      body: 'Relativismo → "no te debo justificación" → "tú introdujiste eso" → "es solo lo que la palabra significa" → insulto. Cada estación se abandona sin defenderla. La conclusión no se mueve; lo que rota es la munición.',
      tactics: ['moving_goalposts', 'relativismo_moral', 'inversion_carga'], frameworks: ['respetar-no-es-opcion'], from: ['one-way-relativism'] },
    { id: 'insult-seal', level: 3, title: 'El sello-insulto',
      body: '"Ignorant, arrogant, little Bernie, ask your AI friend." No va dirigido al interlocutor: va dirigido al lector, para ahorrarle la tarea de mirar si hubo un argumento. Cubre exactamente el hueco donde debía ir la refutación.',
      tactics: ['insulto_ad_hominem', 'ai_accusation'], frameworks: ['nvc-observacion-sin-juicio'], from: ['retreat-cycle'] },
    { id: 'crop-deaths', level: 3, title: 'Las cosechas también matan',
      body: 'El comodín del body-count. No se niega: se desactiva. Nunca fue una pelea de cifras — una cosa deja una baja, la otra empieza con un esclavo.',
      tactics: ['crop_deaths_flip', 'futility_no_clean_option', 'whataboutism'], frameworks: ['violencia-indirecta-quien-demanda'], from: ['necessary'] },
    { id: 'belief-system', level: 3, title: '"Es tu religión"',
      body: 'Reencuadrar la pregunta moral como credo, culto o ideología exime de contestarla. Nadie debate con una religión; solo la tolera o la rechaza.',
      tactics: ['reencuadre_veganismo_creencia', 'libertarian_autonomy'], frameworks: ['veganismo-no-es-dieta-ni-estilo-de-vida', 'dimension-politica-tomar-posicion'], from: ['one-way-relativism', 'infrastructure'] },
    { id: 'plant-creep', level: 3, title: '"Las plantas también sienten"',
      body: 'Si todo siente, nada cuenta. La jugada estira el criterio hasta romperlo — y solo se estira cuando la pregunta empezó a doler.',
      tactics: ['plant_sentience_equivalence', 'ecocentrismo_conservacion'], frameworks: ['filtro-especie-vs-individuo', 'consideracion-moral-no-cuanto-sufre'], from: ['criterion-unnamed'] },

    // ── 4 · cómo se reproduce ──────────────────────────────────────────────
    { id: 'childhood', level: 4, title: 'Se programa en la infancia',
      body: '"La vaca da leche" se dice a niños que todavía no pueden preguntar. Para cuando pueden, ya está adentro como sentido común, y cuestionarlo se siente como cuestionarse a uno mismo.',
      tactics: ['naturalismo', 'apelacion_normal'], frameworks: ['especismo-se-programa-en-la-infancia', 'mentir-a-las-criaturas-sostiene-el-sistema'], from: ['normal-just', 'infrastructure'] },
    { id: 'language', level: 4, title: 'El idioma lo esconde',
      body: 'Carne, ganado, producto, rendir, dar. Cada palabra hace un trabajo: que el sujeto no aparezca en la oración. El verbo "dar" convierte una apropiación en un regalo.',
      tactics: ['domestication_mutualism'], frameworks: ['premisa-falsa-los-animales-nos-dan', 'lenguaje-carne-hachazo'], from: ['manufactured-availability', 'childhood'] },
    { id: 'half-reality', level: 4, title: 'Solo se normaliza una parte',
      body: 'El pastizal sí; el rastro no. La vaca idílica en el empaque; el ternero removido en ninguna parte. Un sistema que necesita esconder la mitad de lo que hace ya sabe algo sobre esa mitad.',
      tactics: ['welfare_rhetoric', 'data_dump_selectivo'], frameworks: ['normalizar-solo-una-parte-realidad', 'libros-de-texto-niegan-sintiencia'], from: ['welfarism-master-move', 'childhood'] },
    { id: 'no-problem', level: 4, title: 'No sabemos que tenemos un problema',
      body: 'La discriminación que se hereda no se percibe como decisión; se percibe como el mundo. Por eso la pregunta parece agresiva: llega a un lugar donde nadie recuerda haber decidido nada.',
      tactics: ['apelacion_normal', 'futility_no_clean_option'], frameworks: ['no-sabemos-que-tenemos-problema', 'antropoespecismo-universal-deslocalizar'], from: ['childhood', 'belief-system', 'language'] },

    // ── 5 · el fondo ───────────────────────────────────────────────────────
    { id: 'power-draws-circle', level: 5, title: 'El círculo lo dibuja el poder',
      body: 'Si la moral es preferencia, "poseerlos está bien" también lo es, y lo único que decide es quién tiene poder sobre el cuerpo del otro. El relativismo resulta ser la descripción de ese poder, disfrazada de filosofía.',
      tactics: ['relativismo_moral', 'species_hierarchy'], frameworks: ['dominacion-no-es-superioridad-moral', 'violencia-especista'], from: ['retreat-cycle', 'no-problem', 'plant-creep'] },
    { id: 'someone-as-supply', level: 5, title: 'Alguien convertido en suministro',
      body: 'Un ser con conciencia y punto de vista existe como propiedad cuyo cuerpo es un abasto. No como accidente, ni como exceso: como diseño. Es lo que todas las frases de arriba están defendiendo sin decirlo.',
      tactics: ['species_hierarchy', 'peticion_de_principio'], frameworks: ['algo-a-alguien-sujeto-derecho', 'esclavitud-paralelismo', 'especidio'], from: ['property', 'half-reality', 'welfarism-master-move'] },
    { id: 'everyone-inside', level: 5, title: 'Todos estamos adentro',
      body: 'El que pregunta también fue criado ahí. El lurker que lee sin comentar también. No hay un afuera desde donde señalar; hay un adentro desde donde empezar a ver. La pregunta no es una acusación: es la primera vez que se enciende la luz.',
      tactics: [], frameworks: ['antropoespecismo-universal-deslocalizar', 'liberar-la-mente-abre-todas-las-jaulas', 'sembrar-en-el-receptivo'], from: ['no-problem', 'insult-seal', 'crop-deaths'] },
  ],
};
